import { expect, test } from "@playwright/test";
import { spawn } from "node:child_process";

// Bun owns the listener; port 0 avoids all reviewer/live ports. No product build.
let process: ReturnType<typeof spawn>, origin: string;
test.beforeAll(async () => {
  process = spawn("bun", ["-e", 'import {startReviewServer} from "./tests/mobile-hub-review/server.ts"; import {buildDesignSystemAssets} from "./tests/mobile-hub-review/design-system-assets.ts"; const s=await startReviewServer({port:0,assets:new Map(),designSystemAssets:await buildDesignSystemAssets()}); console.log(s.url);'], { cwd: new URL("../..", import.meta.url).pathname });
  origin = await new Promise<string>((resolve, reject) => { process.stdout!.once("data", data => resolve(String(data).trim())); process.once("error", reject); process.once("exit", code => reject(new Error(`Reference server exited ${code}`))); });
});
test.afterAll(() => { process?.kill("SIGTERM"); });
test("product folder chooser traverses, chooses and cancels without backend calls", async ({ page }) => {
  const calls: string[] = [], failures: string[] = [];
  page.on("request", request => { if (request.method() !== "GET" || ["fetch", "xhr"].includes(request.resourceType())) calls.push(request.url()); });
  page.on("pageerror", error => failures.push(error.message));
  await page.goto(origin + "/review/design-system");
  const launch = page.getByRole("button", { name: /Choose Hub folder/ });
  const picker = page.getByRole("region", { name: "Choose Folder", exact: true });
  await launch.click();
  await expect(picker).toHaveClass(/mh-folder-picker/);
  await expect(picker.getByRole("heading", { name: "example", exact: true })).toBeVisible();
  await expect(picker.locator("header").getByRole("button", { name: "Choose", exact: true })).toBeEnabled();
  await expect(picker.getByRole("button", { name: /More|New folder|Create workspace/i })).toHaveCount(0);
  await picker.getByRole("button", { name: "projects", exact: true }).click();
  await expect(picker.getByRole("heading", { name: "projects", exact: true })).toBeVisible();
  await expect(page.locator("#local-result")).toHaveText("Examples ready. No backend operations.");
  await picker.locator("header").getByRole("button", { name: "Choose", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Chosen folder: /example/projects. Local only; no backend changes.");
  await expect(launch).toBeFocused();
  await launch.click();
  await picker.getByRole("button", { name: "empty", exact: true }).click();
  await expect(picker.getByText("This folder has no subfolders.")).toBeVisible();
  await picker.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Folder selection canceled. No backend changes.");
  await expect(launch).toBeFocused();
  await launch.click();
  await picker.getByRole("button", { name: "Unavailable", exact: true }).click();
  await expect(picker.getByRole("alert")).toContainText("Static example");
  await expect(picker.getByRole("button", { name: "Choose", exact: true })).toBeDisabled();
  await picker.getByRole("button", { name: "Return to folder: /example", exact: true }).click();
  await expect(picker.getByRole("heading", { name: "example", exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(picker).toHaveCount(0);
  await expect(launch).toBeFocused();
  expect(calls).toEqual([]); expect(failures).toEqual([]);
});
test("real recipes, local task lifecycle and responsive reference", async ({ page }, testInfo) => {
  const mutations: string[] = [], failures: string[] = [];
  page.on("request", request => { if (request.method() !== "GET") mutations.push(request.url()); });
  page.on("pageerror", error => failures.push(error.message));
  await page.goto(origin + "/review/design-system");
  await expect(page.getByRole("heading", { name: "Uatu Web design system" })).toBeVisible();
  expect(await page.evaluate(() => document.activeElement?.tagName)).toBe("BODY");
  for (const id of ["facts", "navigation", "fields", "switches", "choices", "notice", "review", "tasks-example"]) await expect(page.locator(`#${id}`)).toBeAttached();
  await expect(page.getByRole("switch")).toHaveCount(3);
  await expect(page.getByRole("switch", { name: "Unavailable switch" })).toBeDisabled();
  await page.getByRole("switch", { name: "Show hidden files" }).check();
  await page.getByRole("radio", { name: "Top", exact: true }).check();
  await expect(page.getByRole("radio", { name: "Bottom", exact: true })).not.toBeChecked();
  await page.getByLabel("Display name", { exact: true }).fill("Local draft");
  await expect(page.getByRole("button", { name: "Unavailable action", exact: true })).toBeDisabled();
  await expect(page.locator(".mh-list-more")).toHaveCount(0);
  await page.getByRole("button", { name: "Run local action", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Local action ran. No backend changes.");
  await expect(page.locator(".mh-task")).toHaveCount(0);
  for (const [selector, title] of [["[data-action=local-destination]", "Example credential details"], ["[data-flow=local-list]", "Example workspace details"]]) {
    await page.locator(selector!).click();
    const detail = page.getByRole("region", { name: title, exact: true });
    await expect(detail).toBeVisible();
    await expect(page.getByRole("alertdialog")).toHaveCount(0);
    await expect(detail.locator("input, select, [data-action=commit-sheet]")).toHaveCount(0);
    await expect(detail.getByRole("heading")).toBeFocused();
    await page.screenshot({ path: testInfo.outputPath(`${title!.replaceAll(" ", "-")}-390.png`) });
    await detail.getByRole("button", { name: "Back", exact: true }).click();
    await expect(page.locator(selector!)).toBeFocused();
  }
  await page.getByRole("button", { name: "Review local draft", exact: true }).click();
  const review = page.getByRole("region", { name: "Review local draft", exact: true });
  await expect(review).toBeVisible();
  await expect(page.getByRole("alertdialog")).toHaveCount(0);
  await expect(review.locator("input, select")).toHaveCount(0);
  await expect(review.getByText("Current", { exact: true })).toBeVisible();
  await expect(review.getByText("After", { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("review-fullpage-390.png") });
  await review.getByRole("button", { name: "Apply locally", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Local example completed. No backend changes.");
  await page.getByRole("button", { name: "Try editor", exact: true }).click();
  await expect(page.locator('[data-task-kind="editor"] h1')).toBeFocused();
  await page.getByLabel("Example display name").fill("Changed locally");
  const editor = await page.locator('[data-task-kind="editor"]').boundingBox();
  expect(editor!.width).toBe(page.viewportSize()!.width); expect(editor!.height).toBe(page.viewportSize()!.height);
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Try editor", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Remove example…", exact: true }).click();
  await expect(page.getByRole("alertdialog")).toBeVisible();
  await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeFocused();
  await page.keyboard.press("Shift+Tab");
  await expect(page.getByRole("button", { name: "Remove locally", exact: true })).toBeFocused();
  await page.screenshot({ path: testInfo.outputPath("confirmation-390.png") });
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Remove example…", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Remove example…", exact: true }).click();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByRole("alertdialog")).toHaveCount(0);
  await page.getByRole("button", { name: "Try local pending / error" }).click();
  await page.getByRole("button", { name: "Simulate pending" }).click();
  await expect(page.locator('[data-task-kind="editor"]')).toHaveAttribute("aria-busy", "true");
  await expect(page.getByRole("alert")).toContainText("Local simulated failure");
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Dismiss", exact: true }).click();
  await expect(page.locator("[data-shared-uid]")).toHaveCount(0);
  expect(await page.evaluate(() => Object.keys(localStorage).filter(key => key.startsWith("uatu.hub.notice")))).toEqual([]);
  for (const [width, height, size, colorScheme] of [[320, 568, "100%", "light"], [390, 400, "100%", "dark"], [390, 844, "200%", "dark"]] as const) {
    await page.setViewportSize({ width, height });
    await page.emulateMedia({ colorScheme, reducedMotion: "reduce", contrast: "more" });
    await page.evaluate(size => { document.documentElement.style.fontSize = size; document.querySelector("#catalog")!.scrollTop = 0; }, size);
    expect(await page.locator("#catalog").evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath(`reference-${width}-${height}-${size}.png`) });
  }
  expect(mutations).toEqual([]); expect(failures).toEqual([]);
});
