#!/usr/bin/env bun
// Emits the complete Homebrew formula for a uatu release. The release
// workflow's tap-bump job runs this against the release's SHA256SUMS and
// pushes the output to tjakobsson/homebrew-tap — the formula is
// regenerated wholesale every release, never edited in place, so the job
// is idempotent and safe to re-run from any published release. The edge
// workflow runs the same generator with `--name uatu-edge --tag edge` to
// keep the nightly channel's formula in lockstep (mirroring how
// generate-cask.ts serves both desktop channels). The edge token is
// dash-suffixed, not `uatu@edge`: Homebrew's filename→class mapping only
// rewrites `@` when a digit follows (versioned formulas), so an `@edge`
// formula file can never resolve to a loadable class — unlike cask
// tokens, which are plain strings and keep `@edge` on the desktop side.
//
//   bun run scripts/generate-formula.ts --version 0.1.0 --sums dist/release/SHA256SUMS
//
// Prints the formula to stdout; pass --out <path> to write a file instead.
import path from "node:path";

import { parseSums } from "./generate-cask";

export const FORMULA_ASSETS = [
  "uatu-darwin-arm64.zip",
  "uatu-darwin-x64.zip",
  "uatu-linux-arm64.tar.gz",
  "uatu-linux-x64.tar.gz",
] as const;

export interface FormulaOptions {
  /** Formula name; the edge channel uses "uatu-edge". */
  name?: string;
  /** Release tag holding the assets; defaults to the versioned tag. */
  tag?: string;
}

// Faithful port of Homebrew's Formulary.class_s filename→class rule:
// capitalize, uppercase the letter after -/_/./space, `+` → "x", and
// rewrite `@` as "AT" only when a digit follows ("uatu-edge" → UatuEdge,
// "uatu@1.1" → UatuAT11). Anything the rule can't turn into a valid Ruby
// constant (e.g. "uatu@edge") is unloadable by brew, so the generator
// must only ever be fed tokens this function maps cleanly.
export function formulaClassName(name: string): string {
  return (name.charAt(0).toUpperCase() + name.slice(1).toLowerCase())
    .replace(/[-_.\s]([a-zA-Z0-9])/g, (_, ch: string) => ch.toUpperCase())
    .replace(/\+/g, "x")
    .replace(/(.)@(\d)/, "$1AT$2");
}

export function generateFormula(
  version: string,
  sums: Map<string, string>,
  options: FormulaOptions = {},
): string {
  const name = options.name ?? "uatu";
  const tag = options.tag ?? `v${version}`;
  const sha: Record<string, string> = {};
  for (const asset of FORMULA_ASSETS) {
    const digest = sums.get(asset);
    if (!digest) {
      throw new Error(`SHA256SUMS is missing an entry for ${asset}`);
    }
    sha[asset] = digest;
  }

  const base = `https://github.com/tjakobsson/uatu/releases/download/${tag}`;
  // Stable and edge install the same `bin/uatu`, so exactly one of the
  // two formulas may be installed at a time.
  const conflictsWith = name === "uatu" ? "uatu-edge" : "uatu";

  return `# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-formula.ts).
# Do not edit by hand — the next release overwrites this file.
class ${formulaClassName(name)} < Formula
  desc "Docs-tree watcher with Markdown/AsciiDoc preview and review-load score"
  homepage "https://github.com/tjakobsson/uatu"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/uatu-darwin-arm64.zip"
      sha256 "${sha["uatu-darwin-arm64.zip"]}"
    end
    on_intel do
      url "${base}/uatu-darwin-x64.zip"
      sha256 "${sha["uatu-darwin-x64.zip"]}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/uatu-linux-arm64.tar.gz"
      sha256 "${sha["uatu-linux-arm64.tar.gz"]}"
    end
    on_intel do
      url "${base}/uatu-linux-x64.tar.gz"
      sha256 "${sha["uatu-linux-x64.tar.gz"]}"
    end
  end

  conflicts_with "${conflictsWith}", because: "both install a \`uatu\` binary"

  def install
    bin.install "uatu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uatu --version")
  end
end
`;
}

function readFlag(argv: string[], name: string): string | undefined {
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === name) {
      return argv[i + 1];
    }
    if (arg.startsWith(`${name}=`)) {
      return arg.slice(name.length + 1);
    }
  }
  return undefined;
}

if (import.meta.main) {
  const argv = process.argv.slice(2);
  const version = readFlag(argv, "--version");
  const sumsPath = readFlag(argv, "--sums");
  const outPath = readFlag(argv, "--out");
  const name = readFlag(argv, "--name");
  const tag = readFlag(argv, "--tag");

  if (!version || !sumsPath) {
    console.error(
      "usage: generate-formula.ts --version <X.Y.Z> --sums <SHA256SUMS> [--out <path>] [--name <formula>] [--tag <release-tag>]",
    );
    process.exit(1);
  }

  const sums = parseSums(await Bun.file(sumsPath).text());
  const formula = generateFormula(version, sums, { name, tag });
  if (outPath) {
    await Bun.write(path.resolve(outPath), formula);
    console.error(`wrote ${outPath} (${name ?? "uatu"} ${version})`);
  } else {
    process.stdout.write(formula);
  }
}
