#!/usr/bin/env bun
// Emits the complete Homebrew formula for a uatu release. The release
// workflow's tap-bump job runs this against the release's SHA256SUMS and
// pushes the output to tjakobsson/homebrew-tap — the formula is
// regenerated wholesale every release, never edited in place, so the job
// is idempotent and safe to re-run from any published release.
//
//   bun run scripts/generate-formula.ts --version 0.1.0 --sums dist/release/SHA256SUMS
//
// Prints the formula to stdout; pass --out <path> to write a file instead.
import path from "node:path";

function readFlag(argv: string[], name: string): string | undefined {
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === name) {
      return argv[i + 1];
    }
    if (arg.startsWith(`${name}=`)) {
      return arg.slice(name.length + 1);
    }
  }
  return undefined;
}

const argv = process.argv.slice(2);
const version = readFlag(argv, "--version");
const sumsPath = readFlag(argv, "--sums");
const outPath = readFlag(argv, "--out");

if (!version || !sumsPath) {
  console.error("usage: generate-formula.ts --version <X.Y.Z> --sums <SHA256SUMS> [--out <path>]");
  process.exit(1);
}

// SHA256SUMS format: "<hex sha256>  <filename>" per line (sha256sum output).
const sums = new Map<string, string>();
for (const line of (await Bun.file(sumsPath).text()).split("\n")) {
  const match = line.trim().match(/^([0-9a-f]{64})\s+\*?(.+)$/);
  if (match) {
    sums.set(match[2], match[1]);
  }
}

const ASSETS = [
  "uatu-darwin-arm64.zip",
  "uatu-darwin-x64.zip",
  "uatu-linux-arm64.tar.gz",
  "uatu-linux-x64.tar.gz",
] as const;

const sha = Object.fromEntries(
  ASSETS.map(asset => {
    const digest = sums.get(asset);
    if (!digest) {
      console.error(`SHA256SUMS is missing an entry for ${asset}`);
      process.exit(1);
    }
    return [asset, digest];
  }),
) as Record<(typeof ASSETS)[number], string>;

const base = `https://github.com/tjakobsson/uatu/releases/download/v${version}`;

const formula = `# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-formula.ts).
# Do not edit by hand — the next release overwrites this file.
class Uatu < Formula
  desc "Docs-tree watcher with Markdown/AsciiDoc preview and review-load score"
  homepage "https://github.com/tjakobsson/uatu"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/uatu-darwin-arm64.zip"
      sha256 "${sha["uatu-darwin-arm64.zip"]}"
    end
    on_intel do
      url "${base}/uatu-darwin-x64.zip"
      sha256 "${sha["uatu-darwin-x64.zip"]}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/uatu-linux-arm64.tar.gz"
      sha256 "${sha["uatu-linux-arm64.tar.gz"]}"
    end
    on_intel do
      url "${base}/uatu-linux-x64.tar.gz"
      sha256 "${sha["uatu-linux-x64.tar.gz"]}"
    end
  end

  def install
    bin.install "uatu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uatu --version")
  end
end
`;

if (outPath) {
  await Bun.write(path.resolve(outPath), formula);
  console.error(`wrote ${outPath} (uatu ${version})`);
} else {
  process.stdout.write(formula);
}
