#!/usr/bin/env bun
// Emits the complete Homebrew cask for a UatuCode Desktop release. The
// release workflow's tap-bump job runs this against the release's
// SHA256SUMS and pushes the output to tjakobsson/homebrew-tap — like the
// formula (generate-formula.ts), the cask is regenerated wholesale every
// release, never edited in place, so the job is idempotent.
//
// The app archives only exist on releases built with Developer ID signing
// secrets configured; the caller is expected to skip cask generation when
// SHA256SUMS has no UatuCode-Desktop entries (exit code 2 signals that).
//
//   bun run scripts/generate-cask.ts --version 0.2.0 --sums SHA256SUMS
//
// Prints the cask to stdout; pass --out <path> to write a file instead.
import path from "node:path";

export const CASK_ASSETS = ["UatuCode-Desktop-arm64.zip", "UatuCode-Desktop-x64.zip"] as const;

// SHA256SUMS format: "<hex sha256>  <filename>" per line (sha256sum output).
export function parseSums(text: string): Map<string, string> {
  const sums = new Map<string, string>();
  for (const line of text.split("\n")) {
    const match = line.trim().match(/^([0-9a-f]{64})\s+\*?(.+)$/);
    if (match) {
      sums.set(match[2], match[1]);
    }
  }
  return sums;
}

export function generateCask(version: string, sums: Map<string, string>): string {
  const sha: Record<string, string> = {};
  for (const asset of CASK_ASSETS) {
    const digest = sums.get(asset);
    if (!digest) {
      throw new Error(`SHA256SUMS is missing an entry for ${asset}`);
    }
    sha[asset] = digest;
  }

  const base = `https://github.com/tjakobsson/uatu/releases/download/v${version}`;

  return `# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-cask.ts).
# Do not edit by hand — the next release overwrites this file.
cask "uatu-desktop" do
  version "${version}"

  on_arm do
    sha256 "${sha["UatuCode-Desktop-arm64.zip"]}"
    url "${base}/UatuCode-Desktop-arm64.zip"
  end
  on_intel do
    sha256 "${sha["UatuCode-Desktop-x64.zip"]}"
    url "${base}/UatuCode-Desktop-x64.zip"
  end

  name "UatuCode Desktop"
  desc "Desktop app for uatu, the docs-tree watcher with Markdown/AsciiDoc preview"
  homepage "https://github.com/tjakobsson/uatu"

  depends_on macos: :tahoe

  app "UatuCode Desktop.app"

  zap trash: [
    "~/Library/Preferences/se.coll8.uatucode.desktop.plist",
    "~/Library/WebKit/se.coll8.uatucode.desktop",
  ]
end
`;
}

function readFlag(argv: string[], name: string): string | undefined {
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === name) {
      return argv[i + 1];
    }
    if (arg.startsWith(`${name}=`)) {
      return arg.slice(name.length + 1);
    }
  }
  return undefined;
}

if (import.meta.main) {
  const argv = process.argv.slice(2);
  const version = readFlag(argv, "--version");
  const sumsPath = readFlag(argv, "--sums");
  const outPath = readFlag(argv, "--out");

  if (!version || !sumsPath) {
    console.error("usage: generate-cask.ts --version <X.Y.Z> --sums <SHA256SUMS> [--out <path>]");
    process.exit(1);
  }

  const sums = parseSums(await Bun.file(sumsPath).text());
  if (CASK_ASSETS.some(asset => !sums.has(asset))) {
    console.error("SHA256SUMS has no UatuCode-Desktop app archives (unsigned release?); not generating a cask");
    process.exit(2);
  }

  const cask = generateCask(version, sums);
  if (outPath) {
    await Bun.write(path.resolve(outPath), cask);
    console.error(`wrote ${outPath} (uatu-desktop ${version})`);
  } else {
    process.stdout.write(cask);
  }
}
